apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: k8s.cluster.dev.masachoco.xyz
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  certManager:
    enabled: true
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-cluster-dev-masachoco-xyz-state-store/k8s.cluster.dev.masachoco.xyz
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1a
      name: a
    # - encryptedVolume: true
    #   instanceGroup: master-ap-northeast-1c
    #   name: c
    # - encryptedVolume: true
    #   instanceGroup: master-ap-northeast-1d
    #   name: d
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-ap-northeast-1a
      name: a
    # - encryptedVolume: true
    #   instanceGroup: master-ap-northeast-1c
    #   name: c
    # - encryptedVolume: true
    #   instanceGroup: master-ap-northeast-1d
    #   name: d
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
    useServiceAccountExternalPermissions: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.25.3
  masterPublicName: api.k8s.cluster.dev.masachoco.xyz
  metricsServer:
    enabled: true
    # insecure: false
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://k8s-cluster-dev-masachoco-xyz-state-store/k8s.cluster.dev.masachoco.xyz/discovery/k8s.cluster.dev.masachoco.xyz
    enableAWSOIDCProvider: true
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  sshKeyName: kops #ec2 の keypair https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/awstasks/sshkey.go#L78
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-northeast-1a
    type: Public
    zone: ap-northeast-1a
  - cidr: 172.20.64.0/19
    name: ap-northeast-1c
    type: Public
    zone: ap-northeast-1c
  - cidr: 172.20.96.0/19
    name: ap-northeast-1d
    type: Public
    zone: ap-northeast-1d
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s.cluster.dev.masachoco.xyz
  name: master-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20221206
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  # machineType: t2.micro
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-northeast-1a

# ---

# apiVersion: kops.k8s.io/v1alpha2
# kind: InstanceGroup
# metadata:
#   creationTimestamp: null
#   labels:
#     kops.k8s.io/cluster: k8s.cluster.dev.masachoco.xyz
#   name: master-ap-northeast-1c
# spec:
#   image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20221206
#   instanceMetadata:
#     httpPutResponseHopLimit: 3
#     httpTokens: required
#   machineType: t3.medium
#   maxSize: 1
#   minSize: 1
#   role: Master
#   subnets:
#   - ap-northeast-1c

# ---

# apiVersion: kops.k8s.io/v1alpha2
# kind: InstanceGroup
# metadata:
#   creationTimestamp: null
#   labels:
#     kops.k8s.io/cluster: k8s.cluster.dev.masachoco.xyz
#   name: master-ap-northeast-1d
# spec:
#   image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20221206
#   instanceMetadata:
#     httpPutResponseHopLimit: 3
#     httpTokens: required
#   machineType: t3.medium
#   maxSize: 1
#   minSize: 1
#   role: Master
#   subnets:
#   - ap-northeast-1d

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: k8s.cluster.dev.masachoco.xyz
  name: nodes-ap-northeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20221206
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  # machineType: t2.micro
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - ap-northeast-1a
