apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: dev
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: 834894006862.dkr.ecr.ap-northeast-1.amazonaws.com/k8s-sample-app:latest
          imagePullPolicy: Always
